### ISSUE TITLE
Semaphore Community Grant Round

### ISSUE THREAD

**Issue by aguzmant103** [ethereum/esp-website#233]
Create an ESP grant page like https://esp.ethereum.foundation/merge-data-challenge

- Title: Semaphore Community Grant Round
- Copy of Landing Page: https://docs.google.com/document/d/1q2eK3a-PAd0UEXm9stSaAcly1eU5D_oD/edit
- Link of Image Asset (Hero Banner): https://drive.google.com/file/d/1hkfgMzjG7R2ywuOaF_Y8ktVR0t-Uq49Z/view?usp=sharing
- Copy & input field names/types for the application: https://docs.google.com/spreadsheets/d/1YpA7U94D9t7wV4FabRbKJLB8GHhGpszqukhozhqLplE/edit?usp=sharing
- Copy for the homepage banner, if you'd like one: "Semaphore is a zero-knowledge protocol that allows users to prove their membership of a group and send signals such as votes without revealing their original identity."

**Comment by pettinarip** [comment]
Cool! @aguzmant103 could you give me access to this?

> Link of Image Asset (Hero Banner): https://drive.google.com/file/d/1ZfFgv1wRePSBP0A4cz1d8msUoixSAFx3/view?usp=sharing

I've already sent a request to access it in Drive.

**Comment by aguzmant103** [comment]
Can you check again @pettinarip  https://drive.google.com/drive/folders/1uVy15WRoQFI6GeWmW3G68xy9nLbRbqTr?usp=sharing

**Comment by pettinarip** [comment]
Thanks @aguzmant103 now I can access it

**Comment by aguzmant103** [comment]
@pettinarip  updating the illustration: https://drive.google.com/file/d/1hkfgMzjG7R2ywuOaF_Y8ktVR0t-Uq49Z/view?usp=sharing

**Comment by samajammin** [comment]
Marking this as solved in #234, the pages are live: https://esp.ethereum.foundation/semaphore-grants
