### ISSUE TITLE
Layer 2 Community Grants 2022

### ISSUE THREAD

**Issue by Rodrigolvc** [ethereum/esp-website#240]
Create an ESP grant page like https://esp.ethereum.foundation/merge-data-challenge

Title: Layer 2 Community Grants 2022
Launch date: October 24th, 2022

Markdown of Landing Page: 
https://hackmd.io/@BcrNKqoOR1OZEFsNu7su9w/SyQEev5Wi

Project wishlist: 
https://hackmd.io/@BcrNKqoOR1OZEFsNu7su9w/SkdvCP7zs

Link of Image Asset (Place Holder until Tomo creates one): 
https://drive.google.com/file/d/12f-X7na_KxBptYtQtzhD9ecAFpmWIvpn/view?usp=sharing

Copy & input field names/types for the application: https://docs.google.com/spreadsheets/d/1VyLAS20zTLdVztEsAZcLDdMZU9tNXKtM5LWGDK_vzlY/edit#gid=0

**Comment by samajammin** [comment]
@tomosaito please upload the image(s) here when ready 👍

**Comment by pettinarip** [comment]
@Rodrigolvc I don't have access to the "Project Wish List" (error 403). Although I can access the "Landing Page"

**Comment by Rodrigolvc** [comment]
> @Rodrigolvc I don't have access to the "Project Wish List" (error 403). Although I can access the "Landing Page"

Try this now: https://hackmd.io/@BcrNKqoOR1OZEFsNu7su9w/SkdvCP7zs

Let me know if it still has issues!

**Comment by tomosaito** [comment]
Here's the desktop version image:
https://www.dropbox.com/s/ilx9bqmpekp5qgw/ESP-Layer-2-Community-Grants-2022-hero-image.png?dl=0

And mobile image:
https://www.dropbox.com/s/54hpov5mgkv4fbz/ESP-Layer-2-Community-Grants-2022-hero-image-mobile.png?dl=0

**Comment by samajammin** [comment]
@pettinarip I believe this is complete (solved in https://github.com/ethereum/esp-website/pull/245) - can we close this out?

**Comment by Rodrigolvc** [comment]
We're happy! Pandas are (now) happy. 🐼

**Comment by pettinarip** [comment]
This is done! thanks everyone 💪🏼
