### ISSUE TITLE
Merge Data Challenge Grants Round Edits

### ISSUE THREAD

**Issue by monetmignon** [ethereum/esp-website#242]
https://esp.ethereum.foundation/merge-data-challenge/apply

- We still need a web connection for all the new inquiries to be input to a google sheet. This is so evaluators who do no have a Salesforce license can still view and evaluate the data. We can just use a new sheet, within this existing spreadsheet: https://docs.google.com/spreadsheets/d/12eVrg745byYwa5QZqefp7Ip0SzOBUkO6eETJdBI8X34/edit#gid=0
- There seems to be a bug with the Website field? although the front end form does not show `https://` all the website fields are containing doubles of the `https://`
![image](https://user-images.githubusercontent.com/85249567/194114867-8f370035-f5cf-448b-89ea-7bfb6a70461a.png)
![image](https://user-images.githubusercontent.com/85249567/194114897-450f0595-f3e8-4a9e-bab6-eff5304b14dd.png)

**Comment by pettinarip** [comment]
@monetmignon these issues were fixed. Closing it.
