### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by prairienotes** [ethereum/esp-website#252]
Would it be possible to hide the "Join our newsletter" section for the time being? We're no longer running our newsletter, but we're still getting regular sign-ups for it 😅

![image](https://user-images.githubusercontent.com/120090715/206400948-96173240-2b9c-4edb-b4d3-2cbfba053dd3.png)

**Comment by pettinarip** [comment]
Its hidden now @prairienotes 🙏🏼
