### ISSUE TITLE
Update Referrals field to Long Text field on ESP forms

### ISSUE THREAD

**Issue by monetmignon** [ethereum/esp-website#268]
we would like to update this field, on both https://esp.ethereum.foundation/applicants/small-grants/apply and https://esp.ethereum.foundation/applicants/project-grants/apply:
"Did anyone recommend that you submit an application to the Ecosystem Support Program? If so, who?"
Help Text: _Please submit the person's name only. This is not required._

Salesforce Field Mapping:
[Referrals](https://ef-esp.lightning.force.com/lightning/setup/ObjectManager/Lead/FieldsAndRelationships/00N5J000000QRe8/view) | Referrals__c	| Text(150)
<hr>
to be a long text field and written as such:

"Did anyone recommend that you submit an application to the Ecosystem Support Program?"
Help Text: _Please include the person's name and details of their referral._

Change from one line text box to a text area with 3 line breaks.

Referrals | Referrals__c | Long Text Area(32768)
<hr>
The ESP team can update the field's data type in Salesforce, once the front end change has been made

**Comment by pettinarip** [comment]
@monetmignon Quickly checking where we are currently using the `Referrals__c` field, we have:

- Small grants
  - `Did anyone recommend that you submit an application to the Ecosystem Support Program? If so, who?`
  - Help text: `Please submit the person's name only. This is not required.`
- Project grants
  - `Did anyone recommend that you contact Ecosystem Support?`
  - Help text: `Please write the name of the person who recommended that you apply.`
- Ecodev grants
  - `How did you hear about Ethereum Foundation grant funding?`
  - Help text: none

Should I change those texts on all the 3 forms? or just the ones you mentioned (Small and Project grants)?

**Comment by monetmignon** [comment]
i saw it was inconsistent across the forms, let's go ahead and make this question consistent across all three forms

**Comment by pettinarip** [comment]
Completed @monetmignon
