### ISSUE TITLE
Minor tweak to website content

### ISSUE THREAD

**Issue by prairienotes** [ethereum/esp-website#286]
We're hoping to make some minor amendments to the content on the ESP website:

1. On the ESP website's homepage (https://esp.ethereum.foundation/), we'd like to change the "open source projects" phrase to "free and open source projects". 
![image](https://github.com/ethereum/esp-website/assets/120090715/f590759f-abcb-4bdd-9643-c2db45325f7e)
So, the entire paragraph should read as "We award dozens of grants each quarter, across a variety of categories. We support free and open source projects that strengthen Ethereum's foundations, with a particular focus on builder tools, infrastructure, research, community resources and other public goods. Funding is generally directed toward supporting builders rather than end users."

2. On the ESP website's What We Support page (https://esp.ethereum.foundation/about), we'd like to change the last sentence of the first paragraph to "The work we support is free, open-source, non-commercial, and built for positive sum outcomes."
![image](https://github.com/ethereum/esp-website/assets/120090715/37986cd3-3370-4e1b-b57f-19f27122115b)

3. On the header of the ESP website's What We Support page (https://esp.ethereum.foundation/about), we'd like to change the sentence to "We provide grants and other support for free and open-source projects that strengthen Ethereum's foundations, with a particular focus on builder tools, infrastructure, research and public goods."
![image](https://github.com/ethereum/esp-website/assets/120090715/97e098a3-69d3-4bf5-8155-0da5041f7d94)

Thank you!!

**Comment by pettinarip** [comment]
Will add these changes soon (this week) @prairienotes

**Comment by pettinarip** [comment]
@prairienotes this is done. LMK if you have any other request :)
