### ISSUE TITLE
No confirmation email received after 1 day 

### ISSUE THREAD

**Issue by clearloop** [ethereum/esp-website#310]
**Describe the bug**

**To Reproduce**

submit a small grant

**Expected behavior**

receive a confirmation mail after some time, for me I have waited for 1 day and no confirmation email received

**Screenshots**

<img width="1491" alt="Screenshot 2023-08-08 at 17 42 52" src="https://github.com/ethereum/esp-website/assets/26088946/f8dbf99a-b842-4ea1-b75c-851db0b68cf6">

**Desktop (please complete the following information):**

- OS: osx
- Browser: chrome
- Version: 115.0.5790.114

**Additional context**

Also the link of `Small Grants About Page is broken`

https://esp.ethereum.foundation/applicants/small-grants/applicants/small-grants

**Comment by pettinarip** [comment]
This issue was fixed in SF side.
