### ISSUE TITLE
High traffic to /es/404.html

### ISSUE THREAD

**Issue by catsnackattack** [ethereum/esp-website#32]
/es/404.html is currently the highest-viewed page on the site - https://analytics.google.com/analytics/web/#/report/content-pages/a145235410w206916942p199713718/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:~2Fes~2F404.html

It's plausible this is a result of a mistyped link that for some reason became very popular - which I'm looking into, but I haven't found any leads there so far. Can we look into whether there is some broken pathway in play?

**Comment by samajammin** [comment]
Thanks for reporting this! 

I just checked the codebase & there's no faulty /es/ links. Looking at the single spanish page we have:
https://esp.ethereum.foundation/es/local-grants/honduras/
There's no broken links from that page.

Our redirect (https://esp.ethereum.foundation/honduras) also appears to be working fine.

My best theory at the moment is that a user hitting that Honduras page sees the /es/ path in the URL, then navigates to a different page (e.g. by clicking on https://esp.ethereum.foundation/en/faq/ in the navbar), then tries to edit the path manually to https://esp.ethereum.foundation/es/faq/ in the hopes that there's a spanish version of the page.

I welcome any other ideas!
