### ISSUE TITLE
Academic Grants Round Copy Edits

### ISSUE THREAD

**Issue by jamnuel** [ethereum/esp-website#333]
Please make the following copy edits to the PGR landing page: https://deploy-preview-330--ecosystem-support.netlify.app/academic-grants
Edits are in **bold**

- [ ] **Introductory text**: 
In 2023, we received an astounding 250 applications, **which highlighted** the global academic community’s growing interest in Ethereum. This year, we aim to build on this momentum by inviting even more researchers and institutions from more countries to participate. **Through** this wave of grants, the Ethereum Foundation underscores its commitment to supporting rigorous academic work that addresses key challenges and unlocks new opportunities.

- [ ] **Submit proposal** section: Move the following text from the "Application requirements" section to this section:

- Applications are open to individuals, teams, and organizations. Individual researchers with academic backgrounds, research centers, universities, think-tanks, educators and other stakeholders interested in Ethereum research

- Undergraduate researchers will require a postdoctoral advisor

- [ ] **Selection criteria**: Move the following text from the "Application requirements" section to this section:
- Applications are selected for funding on a case-by-case basis. You may submit more than one application as long as each proposal is unique and meets the requirements and goals of this round. 

- [ ] **Selection criteria**: update copy to read:
Applications are selected for funding on a case-by-case basis. You may submit more than one application as long as each proposal is unique and meets the requirements and goals of this round. Submissions will be reviewed using the following considerations. Note: depending on the proposal, some criteria might not be applicable.

- [ ] **Deadline**: Move the following text from the "Application requirements" section to this section:
- Decisions will be emailed 6 weeks after the application deadline.

- [ ] **Deadline**: update copy to read:
The deadline for proposals is **Monday, March 5th, 2024**. We will follow-up regarding your submission by email. Decisions will be emailed **6-8 weeks** after the application deadline.

- [ ] **Eligibility criteria**: edit bullet points
- Projects must produce formal academic research
- Research output must be open-access with a free and permissive license

Thank you! Please see any additional notes from Rodrigo regarding copy edits.

**Comment by jamnuel** [comment]
Webform edits:

- [ ] "If applying as an Institution, please specify its name" is a required question that shows up no matter what capacity picklist option is selected. We should probably name it "Institution or Organization" 
- [ ] the Countries of team picklist "If you are a team of distributed researchers, please indicate where your fellow researchers are located" is required, but it doesn't have a red asterisk.

**Comment by pettinarip** [comment]
@jamnuel I've done these updates in #330.
