### ISSUE TITLE
Update Categories List

### ISSUE THREAD

**Issue by monetmignon** [ethereum/esp-website#349]
We'd like to update the Categories list on all three website forms to better reflect what applications we are gathering:
[Office hours](https://esp.ethereum.foundation/applicants/office-hours/apply)
[Small Grants](https://esp.ethereum.foundation/applicants/small-grants/apply)
[Project Grants](https://esp.ethereum.foundation/applicants/project-grants/apply)

Those that are **bold** are new values

**Community Initiative**
Community event
Consensus layer
**Cryptography Research**
**dApp Development**
**Decentralized Identity**
**DeFi**
Developer experience and tooling
**Educational Content**
Execution layer
**Formal Verification**
General research
**Governance**
Layer 2
**NFTs / Digital Art**
**Privacy**
**Security**
**Token Development / Tokenomics**
**UX/UI**
**Zero Knowledge Proofs**
**Zero Knowledge Applications**
Other

**Comment by monetmignon** [comment]
API Mappings listed on second sheet for your reference: https://docs.google.com/spreadsheets/d/1_xS-P2csw4aIZjhlIA1jp3v36RC-demsy7W1Eogav6g/edit#gid=1195422348

**Comment by pettinarip** [comment]
@monetmignon sounds good!

One question, just to confirm, do we want to show this exact list in all 3 forms? Asking because, at the moment, the Project Grants list is a little different than the others. It doesn't have the "Community event" option. Should I continue doing that or not?

**Comment by monetmignon** [comment]
ahh, yeah. we are still wanting Community Event to have its own form sometime soon (I thought a PR had been submitted maybe?) for now, that can be the only value excluded from the Project Grants form. Let me know if that works or if you have more questions. thanks!

**Comment by pettinarip** [comment]
Done!
