### ISSUE TITLE
Finance Request: Layer 2

### ISSUE THREAD

**Issue by monetmignon** [ethereum/esp-website#360]
We'd like to add three questions to the [Grantee Finance Form](https://esp.ethereum.foundation/applicants/grantee-finance)

IF `Layer 2 Payment` = TRUE, Show two questions:

* `Which Layer 2 Network?`
Help Text: `These are the networks we currently support`
Data Type: `Picklist`
Values: `Arbitrum`, `Optimism`
Salesforce Mapping: 
Layer 2 Network | Layer_2_Network__c | Picklist

* Optional Question: `If the Layer 2 network you would like is not available, please let us know which networks you would like supported.`
Help Text: `This question is optional and meant to help the disbursement team gather data on which Layer 2 networks are most requested. You may choose more than one.`
Data Type: `Multi-picklist`
Values: 
```
ApeX
Base
Blast
Gnosis Chain
Linea
Loopring
Manta Pacific
Mantle
Metis
Polygon zkEVM
Scroll
Starknet
zkSync Era
Other
```
Salesforce Mapping:
Layer 2 Network Options | Layer_2_Network_Options__c | Picklist (Multi-Select)

* If `Other` chosen, provide open text field
Help Text: `If the L2 you want supported is not listed, please provide the name`
Salesforce Mapping
Layer 2 Network Other | Layer_2_Network_Other__c | Text Area(255)

Remove this from help text for `Layer 2 Payment` question: "The ESP team will be in touch to confirm which Layer 2 network."

**Comment by monetmignon** [comment]
After review from finance, can we please edit it down to two questions only. The first question can remain the same. The second one:

Optional Question: `If the Layer 2 network you would like is not available, please let us know which networks you would like supported, separated by commas.`
Help Text: `This question is optional and meant to help the disbursement team gather data on which Layer 2 networks are most requested.`
Data Type: `Text field`
Salesforce Mapping:
Layer 2 Network Other | Layer_2_Network_Other__c | Text Area(255)

Therefore, you can remove the 'If Other' question. Thank you!

**Comment by pettinarip** [comment]
@monetmignon I assume that the first question `Which Layer 2 Network?` is required. If so, we will be forced to add "Other" as an option, because this field must always have a value. So if the user selects "Other", we will display the second field mentioned. How does that sound?

**Comment by monetmignon** [comment]
`Which Layer 2 Network?` would only be required if they choose 'Yes' for `Layer 2 Payment`?

Here's the new mapping, let me know if that clarifies things!
https://docs.google.com/spreadsheets/d/1KufvV-oMf7v0DMzW9qNK_J-r3kwQt622nyi1cwhOAMk/edit?usp=sharing
