### ISSUE TITLE
Edit "Who We Support" Page

### ISSUE THREAD

**Issue by prairienotes** [ethereum/esp-website#362]
We'd like to refresh the grantees listed on our ["Who We Support" page](https://esp.ethereum.foundation/about/who-we-support)

1. We'd like the "Latest Grantees" header to be edited to "Recent Grantees"

2. Please remove the existing list of grantees and update them to the ones on this list: https://docs.google.com/document/d/1oYmfYo8nYVFKpYlTCXFqanFaBFE5oIGdgf5MWMTwjI0/edit?usp=sharing

3. Please remove the existing "User experience" category.

Thank you!

**Comment by pettinarip** [comment]
@prairienotes a few questions on the 2nd point. We currently read the grants from [this spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vQbZUomkFHErSQslSFzdRNBPW-6iYXM4103VLkFvOngrv_SX2R4HmRiz78rUJU2widU-hj0kA8ZxQor/pub?gid=0&single=true&output=csv) which is much easier to read from a code perspective than a text document.

I'd like to know if there are any issues with converting this doc to a spreadsheet. Similar as the example I mentioned.

This is all assuming that we want to keep this information in a Google doc or spreadsheet. If we don't really need to store this information in the cloud, I could just put this data in a local file and read it from there.

**Comment by prairienotes** [comment]
@pettinarip Converted the doc to a spreadsheet! https://docs.google.com/spreadsheets/d/1YokuTlUfLEog-i9zAPsb7ypOlgYWn_RyQOp0VOlH_xw/edit?usp=sharing

Let me know if there's anything else I can help with :-)

**Comment by pettinarip** [comment]
Great! thanks @prairienotes

**Comment by pettinarip** [comment]
@prairienotes I've created a preview [here](https://deploy-preview-373--ecosystem-support.netlify.app/about/who-we-support). Let me know how it looks.

If everything looks good, I'll need you to make the spreadsheet content **public** (so that we can read it). To do this, you'll need to click on "File" > "Share" > "Publish to Web" and then select the "csv" format.
![image](https://github.com/ethereum/esp-website/assets/468158/c4d87fc7-d9c9-48d6-b6fa-559d20883d1f)

Once you get the generated link, send it to me and we should be good to go. Thanks!

**Comment by prairienotes** [comment]
@pettinarip It's been published! https://docs.google.com/spreadsheets/d/e/2PACX-1vQAAwSEDH8dwW5gTHeWjBaV9g7xUz8-LE4YOK2-79cZadZRO7t6-gAALrrpKx8vtHPDD4EjPZaVsMSH/pub?output=csv

On the preview it looks like some projects are missing though? There should be four projects listed for the Community & education, Developer experience & tooling, Execution layer, Layer 2, and Other categories.

Thank you!

**Comment by pettinarip** [comment]
Thanks @prairienotes!

> On the preview it looks like some projects are missing though? There should be four projects listed for the Community & education, Developer experience & tooling, Execution layer, Layer 2, and Other categories.

Uhmm good catch. I think I know what is going on, I had to filter some empty rows on my first test and that may be filtering more things than I wanted. Should be an easy fix.

**Comment by pettinarip** [comment]
@prairienotes updated and fixed. LMK if it looks good now.

**Comment by prairienotes** [comment]
@pettinarip It looks great! 😄 

Except I just realized there's a small typo in the "Nimbus by Status" project description (under Execution layer). It should be, "Continued development of the Nimbus execution layer client, continuing to productionize by improving performance and stability as well **as** performing R&D on light clients and creating public documentation." I've edited this in the spreadsheet too ~

**Comment by pettinarip** [comment]
Great!

Keep in mind that the spreadsheet is the source of this data. Every time we publish the website, we are fetching this data again to build the page. So, if you modify that document, you will see those changes on the website.

Ok, I'll let the team know that this is ready for review. Thanks

**Comment by pettinarip** [comment]
Its live now @prairienotes https://esp.ethereum.foundation/about/who-we-support

**Comment by prairienotes** [comment]
Amazing, thank you @pettinarip! 🙏🏻
