### ISSUE TITLE
PSE Form Question update

### ISSUE THREAD

**Issue by monetmignon** [ethereum/esp-website#375]
hi! We just need one question to please be updated on the front end of this form. https://esp.ethereum.foundation/pse-sponsorships/apply

Current: `Why are you interested in quadratic funding?`
New: `Why are you interested in receiving this funding?`

**Mapping:** https://docs.google.com/spreadsheets/d/1TTpD8q3g2RvjhyuWThMFKnIXBV0cJnMVItWvN9KX2kE/edit#gid=604474899

**Comment by nhsz** [comment]
Updated
