### ISSUE TITLE
PSE Grants Application Webform

### ISSUE THREAD

**Issue by jamnuel** [ethereum/esp-website#385]
The Privacy and Scaling Explorations team would like a front-end application form that sends submissions to our Salesforce instance as Leads
- Form to be hosted on the ESP website
- Form will be hidden on the website; PSE team will have private URL to share
- Form has 4 sections, see headers in mapping below.
- Please use same hero image as here: https://esp.ethereum.foundation/pse-sponsorships/apply
-- _OPTIONAL & UNRELATED_: We may want to update the header on the PSE Sponsorship form to say: "Submit Sponsorship Request to Privacy & Scaling Explorations"

Salesforce mapping here: https://docs.google.com/spreadsheets/d/18NEpCou7Z9t9MKbRwWXH1qKlTo5YK5ZhSxHnnNi7_Xs/edit?usp=sharing

Thanks!

**Comment by pettinarip** [comment]
@jamnuel Sounds good. Is there a hard deadline?

**Comment by jamnuel** [comment]
@pettinarip Aug 30th, if possible

**Comment by pettinarip** [comment]
> @pettinarip Aug 30th, if possible

@jamnuel could it be the next Friday the 6th? because next week I'm OOO.

**Comment by jamnuel** [comment]
All good @pettinarip, thanks for letting us know :)

**Comment by mitsu1124** [comment]
Hey. Thank you for the form. Im Mitsu from PSE. 

I have two questions. 

![image](https://github.com/user-attachments/assets/502b9623-93e9-4d1c-addd-40a82eb0af01)

- What is the maximum number of letters we can set for each field? In my past experience, there were applications with more than 2,000 letters for Project Detail, Development Roadmap, and Roadmap Milestones. 

- Are there any type of symbols or characters that applicants cannot include in a field such as Development Roadmap and Roadmap Milesotnes? e.g., a piece of snippet

**Comment by jamnuel** [comment]
Re: character limit - we should increase this for these long text area fields. the max in salesforce is 32768.

**Comment by mitsu1124** [comment]
> The text fields support any combination of letters, numbers, or symbols. What would a snippet be in this case?

Let me list actual pieces of codes from the past proposals: 

```
abiEncode(
    bytes     proof         
    uint256   relayerHash
    uint256   subjectSalt
    uint256   subjectStr    // (TODO: this type probably need to be changed)
)
```
```
Assert emailNullifier==POSEIDON_HASH(headerHashInt,rsaSignatureIntOld,fromEmailAddr||zeroPaddings,numBytes(fromEmailAddr)).

```
```
{
    post: "actualPostCID",
    votes: [authorVotes]
}
```

**Comment by mitsu1124** [comment]
> Re: character limit - we should increase this for these long text area fields. the max in salesforce is 32768.

Thank you @jamnuel 
Glad if we could set it as the maximum for Project Detail, Development Roadmap, and Roadmap Milestones.

**Comment by mitsu1124** [comment]
![image](https://github.com/user-attachments/assets/c796ca79-d845-46eb-859f-348856c23cc2)

Glad if we could change the high-lighted text as follows:

Before: Proposals should include a detailed budget breakdown for requested amount.
After: Proposals should include a detailed budget breakdown for the requested amount in the Roadmap Milestones.

**Comment by monetmignon** [comment]
> Glad if we could change the high-lighted text as follows:
> 
> Before: Proposals should include a detailed budget breakdown for requested amount. After: Proposals should include a detailed budget breakdown for the requested amount in the Roadmap Milestones.

This field actually has a 20 character limit, as the intention is for them to only list the currency and amount. So the help text should probably just be "Estimated grant amount, i.e. USD 50,000"
And the budget breakdown should be included in either the Roadmap Overview or Roadmap Milestones section.

**Comment by monetmignon** [comment]
> Let me list actual pieces of codes from the past proposals:
> 
> ```
> abiEncode(
>     bytes     proof         
>     uint256   relayerHash
>     uint256   subjectSalt
>     uint256   subjectStr    // (TODO: this type probably need to be changed)
> )
> ```
> 
> ```
> Assert emailNullifier==POSEIDON_HASH(headerHashInt,rsaSignatureIntOld,fromEmailAddr||zeroPaddings,numBytes(fromEmailAddr)).
> ```
> 
> ```
> {
>     post: "actualPostCID",
>     votes: [authorVotes]
> }
> ```
I believe snippets of code should show up in that same format, with the amount of spaces and tabs, etc. however feel free to submit a test application to see if it does! I would recommend that the hackmd proposals contain a majority of the code.

**Comment by jamnuel** [comment]
@pettinarip I've updated the field mapping here!
https://docs.google.com/spreadsheets/d/18NEpCou7Z9t9MKbRwWXH1qKlTo5YK5ZhSxHnnNi7_Xs/edit?usp=sharing

- Lots of copy changes in form questions and help text.
- Double check field requirement as some of these have changed.
- All fields that have been ~struck through~ need to be removed. 
- Fields highlighted green are new fields that don't currently exist on the form.
- {{{Category}}} is hardwired now.

We are cutting back on the questions required in the form and instead directing applicants to link to a full proposal using the  hackmd proposal template here: https://hackmd.io/@28POrCkqSYCpNAIdvae0ag/r1trYkmIh.


*_Future note_: Once this form is updated, we may want to consider adding body text below the form title like we have in the ESP Grants applications. see screenshot below:

![Screenshot 2024-10-18 at 1 28 55 PM](https://github.com/user-attachments/assets/e8eb2905-9832-44b2-9549-1d3fdaca5e33)

**Comment by pettinarip** [comment]
@jamnuel I've updated the fields. You can see them in the preview <https://deploy-preview-387--ecosystem-support.netlify.app/pse-grants/apply>.

Regarding the body text below the title, no problem. Let me know the copy and we will add it.

Regarding the text field length, we had set a default limit of 2000 characters for most text area fields in the site, but we can adjust this one in particular. What length would you prefer @mitsu1124 in this case, 5000 or more? we could leave it free as well but I would prefer to set a generous limit to avoid potential bugs with the server limits on the payload.

**Comment by jamnuel** [comment]
Edits:

- [ ] Default CurrencyISOCode field value to USD.
- [ ] Update help text for "Proposal URL"
> Include below a link to your detailed project proposal. Use the HackMD proposal template [here](https://hackmd.io/@28POrCkqSYCpNAIdvae0ag/r1trYkmIh).

- [ ] Add the following copy for body text:

> The following webform is used to apply to the Ethereum Foundation's Privacy and Scaling Explorations (PSE) grants program. Answer the following questions thoroughly and create a complete, detailed project proposal using the [HackMD proposal template](https://hackmd.io/_vMHk_W3SrGdVJehilnxvw) to be considered for funding. 
For more information about PSE, visit: https://pse.dev/

> Please note that by submitting this application, you confirm that you have read and agree to our [Privacy Policy](https://ethereum.org/en/privacy-policy/).

**Comment by pettinarip** [comment]
@jamnuel I've added these changes to https://deploy-preview-387--ecosystem-support.netlify.app/pse-grants/apply.

FYI I've also submitted a test application if you'd like to check it out. The created lead id is `00QVj00000CGjn3MAD`.

LMK if you want any other tweaks or changes.

**Comment by jamnuel** [comment]
@pettinarip some minor changes below:

- [ ] Add a line break in header copy for the line "For more information about PSE, visit: https://pse.dev/"
- [ ] Change Company City field to just 'City' and add the following help text: "City that the organization or primary contact is based in."
- [ ] Make City field optional
- [ ] Make Discord field optional


Thank you!

**Comment by pettinarip** [comment]
> @pettinarip some minor changes below:
> 
> * [x]  Add a line break in header copy for the line "For more information about PSE, visit: https://pse.dev/"
> * [x]  Change Company City field to just 'City' and add the following help text: "City that the organization or primary contact is based in."
> * [x]  Make City field optional
> * [x]  Make Discord field optional
> 
> Thank you!

Done1

**Comment by jamnuel** [comment]
Awesome @pettinarip let's ship it!

**Comment by pettinarip** [comment]
Deployed https://esp.ethereum.foundation/pse-grants/apply
