### ISSUE TITLE
Remove Twitter link from Who We Support page

### ISSUE THREAD

**Issue by prairienotes** [ethereum/esp-website#386]
Could we please get help removing a Twitter link on our [Who We Support](https://esp.ethereum.foundation/about/who-we-support) page? It's for the L2 en Espanol project under the Layer 2 section, the Twitter link no longer works hence the removal. The [other link](https://linktr.ee/layer2es) for their project still works and can stay up.

![Untitled](https://github.com/user-attachments/assets/05c6a90b-b6e8-4d51-a29a-9f4235a76e32)

Thank you!

**Comment by minimalsm** [comment]
Hey @prairienotes, I replied to you on Discord, but just to keep everything in context here:

This data comes from a grants recipients Google spreadsheet that I believe your team controls (I cannot edit). Could you please remove the entry for "L2 en Espanol" in the Twitter column?

<img width="864" alt="Screenshot 2024-08-27 at 17 46 34" src="https://github.com/user-attachments/assets/45efaf3b-a2e6-4425-9066-c10cbe463eb0">

After that is done, I can rebuild the project to remove the link. Thanks!

**Comment by prairienotes** [comment]
@minimalsm I just deleted it, thank you so much for the quick response!

**Comment by minimalsm** [comment]
Fixed :)! thanks @prairienotes.

You can close this issue (I don't have permissions :P)
