### ISSUE TITLE
Could not submit application for project grant

### ISSUE THREAD

**Issue by clearloop** [ethereum/esp-website#393]
**Describe the bug**

**To Reproduce**

1. Go to https://esp.ethereum.foundation/applicants/project-grants/apply
2. Fill the form
3. work on the hCaptcha
4. See error: `Something went wrong while submitting, please try again.`
5. open the console, the request path `project-grants` failed with `{"status":"captcha failed"}` or `{"status": "fail"}`

**Expected behavior**
it can submit form

**Screenshots**

<img width="1250" alt="Screenshot 2024-10-24 at 16 39 39" src="https://github.com/user-attachments/assets/6e617be4-e436-4ace-bd98-f5cab464b547">

**Desktop (please complete the following information):**

- OS: OSX
- Browser chrome
- Version 129

**Comment by pettinarip** [comment]
Thank you for reporting the bug @clearloop.

After looking at the logs, I think the main problem is related to the selected fiat currency. As soon as we fix this, I'll let you know so you can try it again.

The captcha bug is a UI bug that we also need to fix. I think we should reset the captcha field after a submission. So the user should complete a new captcha per submission. But this shouldn't block you after we fix the first issue.

**Comment by pettinarip** [comment]
@clearloop the main problem I mentioned regarding the fiat currency is fixed. So let me know if you could try again and see how it goes. Thanks

**Comment by clearloop** [comment]
> @clearloop the main problem I mentioned regarding the fiat currency is fixed. So let me know if you could try again and see how it goes. Thanks

It works now, thanks!
