### ISSUE TITLE
Update PSE Grants Application Field: Related PSE Project

### ISSUE THREAD

**Issue by jamnuel** [ethereum/esp-website#396]
Please make the following change to the PSE Grants webform: https://esp.ethereum.foundation/pse-grants/apply

Field: Related PSE Project (Required)
Edit: Change from open text field to multi-select picklist with the following options:
- Anon Aadhaar
- Bandada
- chiquito
- Discreetly
- DSL Working Group
- ECIP Halo2 Implementation
- Excubiae
- jubmoji.quest
- MACI
- Mopro
- MPC Research
- MPCStats
- nfctap.xyz
- OpenPassport
- p0tion
- P256
- Perpetual Powers of Tau
- PSE Security
- Rate-Limiting Nullifier
- Semaphore
- Summa
- TLSNotary
- Trusted Setups
- VoiceDeck
- WAX
- ZK-ID
- ZK-Kit
- zkemail
- zkEVM Community Edition
- ZKML
- ZKP2P

**Comment by pettinarip** [comment]
Ok @jamnuel. I'll keep sending the selected options as a comma separated text, e.g. `chiquito,Discreetly,ECIP Halo2 Implementation`

**Comment by fedefede8** [comment]
This list is up to date:
Anon Aadhaar
OpenPassport
TLSNotary
ZK Email
zkID Standards
Bandada
Cursive
MACI
Semaphore
ZKP2P
ZKStats/MPCStats
Mopro
RISC-V zkVM
ZK-Kit

**Comment by jamnuel** [comment]
@pettinarip Updated to multi-select picklist on the SF side 🧚
