### ISSUE TITLE
Changes to ESP "Exploring Possibilities" inquiry form

### ISSUE THREAD

**Issue by catsnackattack** [ethereum/esp-website#42]
- Retitle "Exploring Possibilities" -> "General Inquiry"

- Revise questions and help text - requested changes here: https://www.notion.so/efdn/Redo-Exploring-Possibilities-form-b471b1605eb442b6a84a9d8ff3d41a94

- Direct General Inquiry submissions to esp@ethereum.org (Specific Project should still go to Salesforce)

**Comment by samajammin** [comment]
Solved in #52
