### ISSUE TITLE
Add form validation w/ helper text

### ISSUE THREAD

**Issue by samajammin** [ethereum/esp-website#81]
**Is your feature request related to a problem? Please describe.**

Just added some nice form validation for the rollup grants (#77) - we should add the same logic to general inquiries:
https://github.com/ethereum/esp-website/blob/master/src/pages/inquire.js

**Describe the solution you'd like**

Same as #77 - when a given input is taken off focus, it should validate & provide help text if invalid.

**Comment by nhsz** [comment]
@samajammin closing this one as we're already applying form validation on blur
