### ISSUE TITLE
Fix "gatsby-transformer-sharp" warning

### ISSUE THREAD

**Issue by samajammin** [ethereum/esp-website#88]
**Is your feature request related to a problem? Please describe.**

After migration to Gatsby v3 (#84), this warning pops up when running the dev server:

```
warning [gatsby-transformer-sharp] The "fixed" and "fluid" resolvers are now deprecated. Switch to "gatsby-plugin-image" for better performance and a simpler API. See https://gatsby.dev/migrate-images to learn how.
```

**Describe the solution you'd like**

https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide/

**Comment by nhsz** [comment]
Closed as we're not using Gatsby on this site anymore.
